"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var route = express.Router();
var createError = require("http-errors");
var userRoute = require("./users_route/users_route");
var inviteRoute = require("./invite_route/invite_route");
var Message = require("../models/messages.model");
route.use("/", userRoute);
route.use("/", inviteRoute);
module.exports = route;
