"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var route = express.Router();
var createError = require("http-errors");
var userRoute = require("./users_route/users_route");
var inviteRoute = require("./invite_route/invite_route");
var chatRoute = require("./chatRoom_route/chatRoom_route");
route.use("/", userRoute);
route.use("/", inviteRoute);
route.use("/", chatRoute);
module.exports = route;
