FROM node
WORKDIR /app

ENV NEXT_PUBLIC_GQL_PROTOCOL https
ENV NEXT_PUBLIC_GQL_HOST chat-app-gql.up.railway.app

# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY . .
RUN yarn --frozen-lockfile
RUN yarn build

EXPOSE 3000

CMD ["yarn","start:frontend"]
# 6.56 GB