services:
  backend:
    container_name: backend
    restart: on-failure
    build: ./packages/backend
    ports:
      - "4002:4002"
    links:
      - mongo
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    restart: on-failure
    build: ./packages/frontend
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
