FROM node
WORKDIR /app

ENV NEXT_PUBLIC_GQL_PROTOCOL http
ENV NEXT_PUBLIC_GQL_HOST localhost
ENV NEXT_PUBLIC_GQL_PORT 4003

# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY . .
RUN yarn --frozen-lockfile
RUN yarn bootstrap
RUN npx lerna run build --scope=@chat-app/frontend

EXPOSE 3000

CMD ["yarn","start:frontend"]
# 6.56 GB