services:
  backend:
    container_name: backend
    restart: on-failure
    build: ./packages/backend
    ports:
      - "4002:4002"
    links:
      - mongo
  frontend:
    container_name: frontend
    restart: on-failure
    build: ./packages/frontend
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
