GET http://localhost:4001/users/ivo
###
POST http://localhost:4001/users/register
Content-Type: application/json

{
    "username":"user2"
}
###
DELETE http://localhost:4001/users/ivan

###
PUT http://localhost:4001/invites
Content-Type: application/json

{
    "reciever":"ivo",
    "id":"6148c5032c43d41c59f15b87",
    "status":"accepted"
}
### recieved
GET http://localhost:4001/invites/ivo
### accepted
POST http://localhost:4001/invites
Content-Type: application/json

{
    "reciever":"user2",
}
###