version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - ./test/azurite:/data
