version: "3.1"
services:
  mongo-test:
    container_name: mongo-test
    image: mongo
    ports:
      - "27018:27017"
  redis-test:
    container_name: redis-test
    image: redis
    ports:
      - "6380:6379"
  azurite-test:
    container_name: azurite-test
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10001:10000"
    volumes:
      - ./test/azurite:/data
