version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  blob:
    container_name: blob
    image: mcr.microsoft.com/azure-blob-storage
    ports:
      - "1000:1000"
