services:
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - "4001:4001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
