name: Chat_app Integration

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      # - run: docker run -d -p 27017:27017 mongo
      - run: yarn build
      # - run: yarn test
